version: '3.8'

services:
  app:
    build: .
    container_name: electron-ai-app
    environment:
      - NODE_ENV=development
      - DISPLAY=:99
      - ELECTRON_DISABLE_SANDBOX=true
      - ELECTRON_EXTRA_LAUNCH_ARGS=--no-sandbox
      - NODE_OPTIONS=--max_old_space_size=2048
      - TZ=Asia/Jerusalem
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/snd"
    tty: true
    stdin_open: true
    command: sh -c "Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset & node oneclick.js run"
